=== Liteolika/WinShooter-Legacy/Implementation/Common/Data/tblKlubbar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="tblKlubbar"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblKlubbar">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Klubbnr " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="Namn" index-key="Namn " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Klubbnr" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="Namn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Liteolika/WinShooter-Legacy/Implementation/Common/Data/tblKlubbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblKlubbar.xsd">
<tblKlubbar>
<Klubbnr>1</Klubbnr>
<Namn>Danderyds Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>2</Klubbnr>
<Namn>Stockholms Amatör Förening, Pistolsekt.</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>3</Klubbnr>
<Namn>Hedemora FBU-Förening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>4</Klubbnr>
<Namn>F 4 Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>5</Klubbnr>
<Namn>Borås Pistolskyttar</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>10</Klubbnr>
<Namn>Kungl.Flottans If Karlskrona P-Sekt</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>12</Klubbnr>
<Namn>Livgardets Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>13</Klubbnr>
<Namn>Örlogsberga Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>14</Klubbnr>
<Namn>Officerarnes Målskjutningsförbund</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>15</Klubbnr>
<Namn>Visborgs Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>16</Klubbnr>
<Namn>Strängnäs Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>17</Klubbnr>
<Namn>Visbypolisens Idrotts- och Skytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>18</Klubbnr>
<Namn>Livregementets Grenadjärers Skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>19</Klubbnr>
<Namn>Telia Idrottsförening  Jönköping</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>20</Klubbnr>
<Namn>Gagnef-Mockfjärds Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>21</Klubbnr>
<Namn>K 3  IF Skyttesektion</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>22</Klubbnr>
<Namn>I 2  Skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>25</Klubbnr>
<Namn>Eksjö Garnison skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>26</Klubbnr>
<Namn>Flisby Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>27</Klubbnr>
<Namn>Akademiska Veteraners Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>29</Klubbnr>
<Namn>Hällefors Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>30</Klubbnr>
<Namn>Ultuna Skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>31</Klubbnr>
<Namn>Skarps Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>32</Klubbnr>
<Namn>Borlänge Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>33</Klubbnr>
<Namn>Trollhättans FBU-Förening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>34</Klubbnr>
<Namn>Unnaryds Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>35</Klubbnr>
<Namn>Storumans Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>36</Klubbnr>
<Namn>Strömsholms Psk I Löten</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>39</Klubbnr>
<Namn>P 7 skif/ p 7 skytte o idrottsför</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>40</Klubbnr>
<Namn>Sportskytteföreningen I11</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>41</Klubbnr>
<Namn>Sthlms Handikapptransportens Skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>42</Klubbnr>
<Namn>Gripen Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>45</Klubbnr>
<Namn>Hammarstrands Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>46</Klubbnr>
<Namn>Aros Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>47</Klubbnr>
<Namn>Lunds Fbu-Förening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>48</Klubbnr>
<Namn>Almundsryds Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>49</Klubbnr>
<Namn>Vimmerby Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>50</Klubbnr>
<Namn>Pistolklubben Eken</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>51</Klubbnr>
<Namn>Södra Jämtlands Fbu-Förening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>53</Klubbnr>
<Namn>Lima Skyttegille</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>54</Klubbnr>
<Namn>I 15 If Pistolsektion</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>55</Klubbnr>
<Namn>Västerås Pistolskyttar</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>56</Klubbnr>
<Namn>Nyköpings Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>57</Klubbnr>
<Namn>Göteborgs Polismäns If Skyttesekt</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>58</Klubbnr>
<Namn>Malmötullens Skytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>59</Klubbnr>
<Namn>Gotlands Kvinnliga Bilkår</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>60</Klubbnr>
<Namn>S 3 Skytte O If</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>61</Klubbnr>
<Namn>I 21/T3 Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>62</Klubbnr>
<Namn>P 4 Idrottsförening Pistolsektionen</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>63</Klubbnr>
<Namn>Lagadalens Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>64</Klubbnr>
<Namn>Pistolskytteklubben Frövi</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>65</Klubbnr>
<Namn>Rosersberg Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>66</Klubbnr>
<Namn>Jönköpingspolisens Skytte- Och If</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>67</Klubbnr>
<Namn>Kristianstads Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>68</Klubbnr>
<Namn>Gävlepolisens Idrottsförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>70</Klubbnr>
<Namn>Pistolskytteklubben Svea Ing 1</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>71</Klubbnr>
<Namn>Kalmar Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>72</Klubbnr>
<Namn>Lilla Beddinge Skyttegille</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>73</Klubbnr>
<Namn>A 1 Skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>74</Klubbnr>
<Namn>Pistolklubben Orion</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>75</Klubbnr>
<Namn>Åkersberga Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>76</Klubbnr>
<Namn>Västeråspolisens If Skyttesekt.</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>79</Klubbnr>
<Namn>Hörby Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>81</Klubbnr>
<Namn>Hudiksvalls Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>82</Klubbnr>
<Namn>Landskrona Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>83</Klubbnr>
<Namn>Transtrands Skf Pistolsektion</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>84</Klubbnr>
<Namn>S Kinds Fbu Pistolsektion</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>85</Klubbnr>
<Namn>Dala-Floda Pistolskytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>87</Klubbnr>
<Namn>Sportskyttarna Ljungby</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>88</Klubbnr>
<Namn>Hässleholms Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>89</Klubbnr>
<Namn>Stockholms Allmänna Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>90</Klubbnr>
<Namn>Stockholms FBU-Förbunds Skf</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>91</Klubbnr>
<Namn>Södra Älvsborgs Polis If</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>93</Klubbnr>
<Namn>Mo Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>95</Klubbnr>
<Namn>I 4 Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>96</Klubbnr>
<Namn>Göteborgs Resoffsällskap</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>97</Klubbnr>
<Namn>Degerfors Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>98</Klubbnr>
<Namn>Visby Nationalbeväring/Dede Skyttegille</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>99</Klubbnr>
<Namn>Pskf Magnus Stenbock</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>100</Klubbnr>
<Namn>I 16/Lv 6 Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>101</Klubbnr>
<Namn>Åby Skytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>102</Klubbnr>
<Namn>Umeåpolisens Skytte- Och Idrottskl</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>103</Klubbnr>
<Namn>Arvika Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>104</Klubbnr>
<Namn>Laxå Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>106</Klubbnr>
<Namn>Falsterbonäsets Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>107</Klubbnr>
<Namn>Umeå Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>108</Klubbnr>
<Namn>Lycksele Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>109</Klubbnr>
<Namn>Grängesbergs Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>112</Klubbnr>
<Namn>Helsingborgspolisens Skytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>113</Klubbnr>
<Namn>Bräcke Pistolskytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>114</Klubbnr>
<Namn>Svartsjö Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>115</Klubbnr>
<Namn>Forsa Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>116</Klubbnr>
<Namn>Orust Pistolskytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>117</Klubbnr>
<Namn>Orsa Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>118</Klubbnr>
<Namn>Sollebrunns Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>119</Klubbnr>
<Namn>Hackås Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>120</Klubbnr>
<Namn>Handens Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>121</Klubbnr>
<Namn>Eslövs Skyttegilles Pistolklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>122</Klubbnr>
<Namn>Friskyttarnas Skytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>123</Klubbnr>
<Namn>Landvetter Pistolskytteförening</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>124</Klubbnr>
<Namn>Pistolklubben Vanäs</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>125</Klubbnr>
<Namn>Valdemarsviks Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>126</Klubbnr>
<Namn>Lunda Skf Pistolsektionen</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>127</Klubbnr>
<Namn>Filipstads Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>129</Klubbnr>
<Namn>Falköpings Jakt- O Sportskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
<Klubbnr>130</Klubbnr>
<Namn>Ekeby Pistolskytteklubb</Namn>
</tblKlubbar>
<tblKlubbar>
