=== Liteolika/WinShooter-Legacy/Implementation/Common/Data/tblVapen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="tblVapen"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblVapen">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="idV " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="Vapen" index-key="Vapen " primary="no" unique="no" clustered="no"/>
<od:index index-name="Vapennamn" index-key="Vapennamn " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="idV" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Vapennamn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="30"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Vapen" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="A1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:byte"/>
<xsd:element name="A2" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:byte"/>
<xsd:element name="A3" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:byte"/>
<xsd:element name="B" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:byte"/>
<xsd:element name="C" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:byte"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Liteolika/WinShooter-Legacy/Implementation/Common/Data/tblVapen.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblVapen.xsd">
<tblVapen>
<idV>1</idV>
<Vapennamn>AMT 9 mm</Vapennamn>
<Vapen>AMT9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>2</idV>
<Vapennamn>AMT .40</Vapennamn>
<Vapen>AMT40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>3</idV>
<Vapennamn>AMT 10 mm</Vapennamn>
<Vapen>AMT10</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>4</idV>
<Vapennamn>Astra 9 mm</Vapennamn>
<Vapen>As9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>5</idV>
<Vapennamn>Auto-Ordnance .45</Vapennamn>
<Vapen>AO45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>6</idV>
<Vapennamn>Beretta 9 mm</Vapennamn>
<Vapen>Be9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>7</idV>
<Vapennamn>Beretta .40</Vapennamn>
<Vapen>Be40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>8</idV>
<Vapennamn>Bernardelli 9 mm</Vapennamn>
<Vapen>Bd9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>9</idV>
<Vapennamn>BUL 9 mm</Vapennamn>
<Vapen>BUL9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>10</idV>
<Vapennamn>BUL .40</Vapennamn>
<Vapen>BUL40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>11</idV>
<Vapennamn>BUL .45</Vapennamn>
<Vapen>BUL45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>12</idV>
<Vapennamn>Caspian 9 mm</Vapennamn>
<Vapen>Ca9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>13</idV>
<Vapennamn>Caspian .38</Vapennamn>
<Vapen>Ca38</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>14</idV>
<Vapennamn>Caspian 10 mm</Vapennamn>
<Vapen>Ca10</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>15</idV>
<Vapennamn>Caspian .45</Vapennamn>
<Vapen>Ca45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>16</idV>
<Vapennamn>Colt 9 mm</Vapennamn>
<Vapen>C9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>17</idV>
<Vapennamn>Colt .40</Vapennamn>
<Vapen>C40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>18</idV>
<Vapennamn>Colt .45</Vapennamn>
<Vapen>C45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>19</idV>
<Vapennamn>CZ 9 mm</Vapennamn>
<Vapen>CZ9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>20</idV>
<Vapennamn>CZ .40</Vapennamn>
<Vapen>CZ40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>21</idV>
<Vapennamn>Detonics .45</Vapennamn>
<Vapen>De45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>22</idV>
<Vapennamn>FÃ¨g 9 mm</Vapennamn>
<Vapen>F9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>23</idV>
<Vapennamn>Husqvarna/Browning m/07</Vapennamn>
<Vapen>m/07</Vapen>
<A1>1</A1>
<A2>0</A2>
<A3>0</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>24</idV>
<Vapennamn>Browning High Power</Vapennamn>
<Vapen>BHP</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>25</idV>
<Vapennamn>Browning High Power .40</Vapennamn>
<Vapen>BHP40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>26</idV>
<Vapennamn>Fratelli Tanfoglio 9 mm</Vapennamn>
<Vapen>FT9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>27</idV>
<Vapennamn>Fratelli Tanfoglio .40</Vapennamn>
<Vapen>FT40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>28</idV>
<Vapennamn>Glock 17 (m88), 19 (m88B)</Vapennamn>
<Vapen>m/88</Vapen>
<A1>1</A1>
<A2>0</A2>
<A3>0</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>29</idV>
<Vapennamn>Glock 9 mm</Vapennamn>
<Vapen>G9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>30</idV>
<Vapennamn>Glock 10 mm</Vapennamn>
<Vapen>G10</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>31</idV>
<Vapennamn>Glock .40</Vapennamn>
<Vapen>G40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>32</idV>
<Vapennamn>Glock .45</Vapennamn>
<Vapen>G45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>33</idV>
<Vapennamn><![CDATA[Heckler & Koch 9 mm]]></Vapennamn>
<Vapen>HK9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>34</idV>
<Vapennamn><![CDATA[Heckler & Koch .40]]></Vapennamn>
<Vapen>HK40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>35</idV>
<Vapennamn><![CDATA[Heckler & Koch .45]]></Vapennamn>
<Vapen>HK45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>36</idV>
<Vapennamn>High Standard .45</Vapennamn>
<Vapen>HS45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>37</idV>
<Vapennamn>Husqvarna/Lahti m/40</Vapennamn>
<Vapen>m/40</Vapen>
<A1>1</A1>
<A2>0</A2>
<A3>0</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>38</idV>
<Vapennamn>IMI 9 mm</Vapennamn>
<Vapen>IMI9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>39</idV>
<Vapennamn>IMI .41</Vapennamn>
<Vapen>IMI41</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>40</idV>
<Vapennamn>Kimber .40</Vapennamn>
<Vapen>Ki40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>41</idV>
<Vapennamn>Kimber .45</Vapennamn>
<Vapen>Ki45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>42</idV>
<Vapennamn>Kongsberg .45</Vapennamn>
<Vapen>Ko45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>43</idV>
<Vapennamn>KPS 9 mm</Vapennamn>
<Vapen>KPS9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>44</idV>
<Vapennamn>KPS .45</Vapennamn>
<Vapen>KPS45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>45</idV>
<Vapennamn>Llama 9 mm</Vapennamn>
<Vapen>L9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>46</idV>
<Vapennamn>Llama .45</Vapennamn>
<Vapen>L45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>47</idV>
<Vapennamn>MAS 9 mm</Vapennamn>
<Vapen>MAS9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>48</idV>
<Vapennamn>Mauser 7,63 mm</Vapennamn>
<Vapen>M7</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>49</idV>
<Vapennamn>Mauser 9 mm</Vapennamn>
<Vapen>M9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>50</idV>
<Vapennamn>Mauser .40</Vapennamn>
<Vapen>M40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>51</idV>
<Vapennamn>Mauser .45</Vapennamn>
<Vapen>M45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>52</idV>
<Vapennamn>Norinco 9 mm</Vapennamn>
<Vapen>No9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>53</idV>
<Vapennamn>Norinco .45</Vapennamn>
<Vapen>No45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>54</idV>
<Vapennamn>Para-Ordnance 9 mm</Vapennamn>
<Vapen>PO9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>55</idV>
<Vapennamn>Para-Ordnance .40</Vapennamn>
<Vapen>PO40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>56</idV>
<Vapennamn>Para-Ordnance .45</Vapennamn>
<Vapen>PO45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>57</idV>
<Vapennamn>Pardini 9 mm</Vapennamn>
<Vapen>Pa9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>58</idV>
<Vapennamn>Pardini .40</Vapennamn>
<Vapen>Pa40</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>59</idV>
<Vapennamn>Pardini .45</Vapennamn>
<Vapen>Pa45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>60</idV>
<Vapennamn>Parabellum (Luger) 7,65 mm</Vapennamn>
<Vapen>P7</Vapen>
<A1>1</A1>
<A2>0</A2>
<A3>0</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>61</idV>
<Vapennamn>Parabellum (Luger) 9 mm</Vapennamn>
<Vapen>P9</Vapen>
<A1>1</A1>
<A2>0</A2>
<A3>0</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>62</idV>
<Vapennamn>Peters Stahl 9 mm</Vapennamn>
<Vapen>PS9</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>63</idV>
<Vapennamn>Peters Stahl .45</Vapennamn>
<Vapen>PS45</Vapen>
<A1>0</A1>
<A2>0</A2>
<A3>1</A3>
<B>1</B>
<C>0</C>
</tblVapen>
<tblVapen>
<idV>64</idV>
